dir = "H:/230500 Nimo round2_histology_retina/NG210X_enhance/Lectin/";
list = getFileList(dir);
for(i=0;i<list.length;i++){
	title = list[i];
	title = title.substring(7,title.length()-4);

open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step5_OR_shape/"+title+"-(117, 255).tif");
run("Analyze Particles...", "size=0-1000000 clear add");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step4_OR/"+title+"-(117, 255).tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-(117, 255)/OR/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step4_OR_fillhole/"+title+"-(117, 255).tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-(117, 255)/fillhole/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/Lectin/lectin-"+title+".tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-(117, 255)/Lectin/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step4_AND/"+title+"-(117, 255).tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-(117, 255)/AND/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step3_/NG2-"+title+"-(117, 255).tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-(117, 255)/NG2/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step6_skel/"+title+"-(117, 255).tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-(117, 255)/skel/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-line1.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-(117, 255)/is line1/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-line2.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-(117, 255)/is line2/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-line3.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-(117, 255)/is line3/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-roi.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-(117, 255)/is sup/"+title+".csv");
run("Clear Results");
roiManager("Delete");
run("Close All");

open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step5_OR_shape/"+title+"-crop-Renyi.tif");
run("Analyze Particles...", "size=0-1000000 clear add");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step4_OR/"+title+"-crop-Renyi.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-crop-Renyi/OR/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step4_OR_fillhole/"+title+"-crop-Renyi.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-crop-Renyi/fillhole/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/Lectin/lectin-"+title+".tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-crop-Renyi/Lectin/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step4_AND/"+title+"-crop-Renyi.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-crop-Renyi/AND/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step3_/NG2-"+title+"-crop-Renyi.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-crop-Renyi/NG2/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step6_skel/"+title+"-crop-Renyi.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-crop-Renyi/skel/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-line1.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-crop-Renyi/is line1/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-line2.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-crop-Renyi/is line2/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-line3.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-crop-Renyi/is line3/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-roi.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-crop-Renyi/is sup/"+title+".csv");
run("Clear Results");
roiManager("Delete");
run("Close All");

open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step5_OR_shape/"+title+"-Renyi-crop.tif");
run("Analyze Particles...", "size=0-1000000 clear add");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step4_OR/"+title+"-Renyi-crop.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-Renyi-crop/OR/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step4_OR_fillhole/"+title+"-Renyi-crop.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-Renyi-crop/fillhole/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/Lectin/lectin-"+title+".tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-Renyi-crop/Lectin/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step4_AND/"+title+"-Renyi-crop.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-Renyi-crop/AND/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step3_/NG2-"+title+"-Renyi-crop.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-Renyi-crop/NG2/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/NG210X_enhance/_Step6_skel/"+title+"-Renyi-crop.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-Renyi-crop/skel/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-line1.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-Renyi-crop/is line1/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-line2.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-Renyi-crop/is line2/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-line3.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-Renyi-crop/is line3/"+title+".csv");
run("Clear Results");
open("H:/230500 Nimo round2_histology_retina/Lectin10X_enhance_NG2/location/"+title+"-roi.tif");
roiManager("Measure");
saveAs("Results", "H:/230500 Nimo round2_histology_retina/NG210X_enhance/excel/-Renyi-crop/is sup/"+title+".csv");
run("Clear Results");
roiManager("Delete");
run("Close All");
}
